# Thiết lập cấu hình catalog cho Trino

# Khai báo sử dụng thư viện Iceberg
connector.name=iceberg
# Cấu hình catalog
iceberg.catalog.type=jdbc
iceberg.jdbc-catalog.driver-class=org.postgresql.driver
iceberg.jdbc-catalog.comnection-url=jdbc:postgresql://postgres:5432/iceberg_catalog             # Kết nối với postgres
iceberg.jdbc-catalog.connection-password=trust
iceberg.jdbc-catalog.connection-user=admin
# Tính năng mặc định tạo bảng mới bằng định dạng Iceberg
iceberg.jdbc-catalog.default-warehouse-dir=s3a://silver/                 # Kết nối với MiniO
# Cấu hình lưu trữ
hive.s3.endpoint=http://minio:9000
hive.s3.aws-access-key=admin
hive.s3.aws-secret-key=12345678
hive.s3.ss1.enabled=false
hive.s3.path-style-access=true
